#
# This file is part of THM Addons — https://github.com/Leonn170709/THM-Addons
# Copyright (c) THM Addons contributors. Credit the devs, keep the link.
# By using this code you agree to the license terms and to keep your repo public.
#

[versions]
mod-version = "0.3.0"

# Fabric (https://fabricmc.net/develop)
minecraft = "26.2"
fabric-loader = "0.19.5"
fabric-api = "0.161.0+26.2"

# Loom (https://github.com/FabricMC/fabric-loom)
loom = "1.18-SNAPSHOT"

# Meteor (https://github.com/MeteorDevelopment/meteor-client/)
meteor = "26.2-SNAPSHOT"

# Mods

[libraries]
# Tests
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version = "5.13.4" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version = "1.13.4" }

# Fabric base
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

# Meteor client
meteor-client = { module = "meteordevelopment:meteor-client", version.ref = "meteor" }

# Baritone
baritone = { module = "meteordevelopment:baritone", version.ref = "meteor" }

# Mods

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
